adios_attendance/adios_attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendances.urls')),
]

adios_attendance/attendances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'attendances'

urlpatterns = [
    path('', views.home, name='home'),  # 첫 화면 뷰
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('check_in/', views.check_in, name='check_in'),
    path('attendance_list/', views.attendance_list, name='attendance_list'),
    path('signup/', views.signup, name='signup'),
    path('all_attendance_list/', views.all_attendance_list, name='all_attendance_list'),
    path('notice/', views.notice, name='notice'),
    path('notice/<int:notice_id>', views.notice_detail, name='notice_detail'),
    path('notice/add/', views.notice_add, name='notice_add'),
    path('notice/<int:notice_id>/delete/', views.notice_delete, name='notice_delete'),
    path('practice_date/', views.practice_date_list, name='practice_date_list'),
    path('practice_date/add', views.practice_date, name='practice_date'),
    path('practice_date/<int:pk>/', views.practice_date_detail, name='practice_date_detail'),
    path('practice_date/<int:available_date_id>/update_attendance_status/', views.update_attendance_status, name='update_attendance_status'),
    path('practice_date/<int:pk>/delete/', views.delete_practice_date_detail, name='delete_practice_date_detail'),
    path('practice_available/', views.practice_available_list, name='practice_available_list'),
    path('practice_available/<int:practice_available_id>/', views.practice_available_detail, name='practice_available_detail'),
    path('practice_available/add/', views.practice_available_add, name='practice_available_add'),
    path('practice_available/<int:pk>/delete/', views.delete_practice_available, name='delete_practice_available')
]

adios_attendance/attendances/forms.py
from django import forms
from .models import Student, Attendance, AvailableDate, PracticeAvailable, PracticeDateDetail, Notice
from django.contrib import messages

class SignUpForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_id', 'name']
        labels = {
            'student_id': '학번',
            'name': '이름',
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label_suffix = ''

    def clean_student_id(self):
        student_id = self.cleaned_data['student_id']
        if len(str(student_id)) != 10:
            raise forms.ValidationError('학번은 10자리 숫자여야 합니다.')
        return student_id

    def clean_name(self):
        name = self.cleaned_data['name']
        existing_names = Student.objects.filter(name=name)
        if existing_names.exists():
            raise forms.ValidationError('같은 이름이 존재합니다.')
        if not (2 <= len(name) <= 3 and name.isalpha()):
            raise forms.ValidationError('이름은 2~3자리 한글로 입력해야 합니다.')
        return name

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ['user', 'date', 'is_attending']

class LoginForm(forms.Form):
    student_id = forms.CharField(label='학번', max_length=10)
    name = forms.CharField(label='이름', max_length=50)

class DateForm(forms.ModelForm):
    class Meta:
        model = AvailableDate
        fields = ['date', 'content']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'content': forms.Textarea(attrs={'rows': 3}),
        }
        labels = {
            'date': '날짜',
            'content': '내용'
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label_suffix = ''

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(str(content)) > 200:
            raise forms.ValidationError('내용은 200자 이내로 제한합니다.')
        return content

from django import forms
from .models import PracticeAvailable
from django.contrib.auth import get_user_model

from django import forms
from .models import PracticeAvailable

class PracticeAvailableForm(forms.ModelForm):
    class Meta:
        model = PracticeAvailable
        fields = ['date', 'content']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'content': forms.Textarea(attrs={'rows': 3}),
        }
        labels = {
            'date': '연습 불가 날짜',
            'content': '사유',
        }

    def __init__(self, *args, **kwargs):
        super(PracticeAvailableForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.label_suffix = ''

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(str(content)) > 200:
            raise forms.ValidationError('내용은 200자 이내로 제한합니다.')
        return content


class PracticeDateDetailForm(forms.ModelForm):
    class Meta:
        model = PracticeDateDetail
        fields = ['practice_date', 'user', 'is_attending']

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'content']
        labels = {
                    'title': '제목',
                    'content': '내용'
                }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label_suffix = ''

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(str(content)) > 200:
            raise forms.ValidationError('내용은 200자 이내로 제한합니다.')
        return content

adios_attendance/attendances/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import date, timedelta, datetime
from .forms import SignUpForm, AttendanceForm, LoginForm, DateForm, PracticeAvailableForm, NoticeForm
from .models import Student, Attendance, Notice, PracticeAvailable, AvailableDate, PracticeDateDetail
from django.contrib.auth import authenticate, login as auth_login
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.core.paginator import Paginator, Page
from functools import wraps
from django.db.models import Q
import logging


logger = logging.getLogger(__name__)

def home(request):
    return render(request, 'home.html')

def user_login(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        name = request.POST.get('name')

        User = get_user_model()
        try:
            user = User.objects.get(student_id=student_id, name=name)
        except User.DoesNotExist:
            # 사용자가 존재하지 않는 경우
            error_message = '학번 또는 이름이 잘못되었습니다.'
            messages.error(request, error_message)
            return redirect('attendances:user_login')

        # 로그인 처리
        request.session['student_id'] = user.student_id
        request.session['name'] = user.name

        # 로그인 성공 시 대시보드로 리디렉션
        return redirect('attendances:dashboard')

    return render(request, 'login.html',)


def dashboard(request):
    student_id_in_session = request.session.get('student_id')
    student_from_session = Student.objects.filter(student_id=student_id_in_session).first()

    if not student_from_session:
        return redirect('attendances:user_login')

    # 현재 날짜의 출결 정보가 있는지 확인
    todays_attendance = Attendance.objects.filter(user=student_from_session, date=date.today()).exists()

    form = AttendanceForm(request.POST or None)
    thousand_days_date = date(2023, 10, 4)
    sept_twelve_date = date(2023, 9, 12)
    today = date.today()
    days_left_to_sept_twelve = (sept_twelve_date - today).days
    days_left_to_thousand_days = (thousand_days_date - today).days

    if days_left_to_sept_twelve > 0:
        message = f"동아리 박람회까지 {days_left_to_sept_twelve}일 남았다!!!"
    elif days_left_to_thousand_days > 0:
        message = f"천보축전까지 {days_left_to_thousand_days}일 남았다!!!"
    else:
        message = "고생했다 얘들아!!!"

    if request.method == 'POST':
        if form.is_valid():
            # 폼에 학생 정보를 저장한 후 현재 날짜로 출결 정보를 저장합니다.
            attendance = form.save(commit=False)
            attendance.student_id = student_from_session.student_id
            attendance.available_date = AvailableDate.objects.get(date=date.today())
            attendance.save()
            return redirect('attendances:dashboard')

    # 학생의 출결 기록을 가져옵니다. user 필드를 사용하고, available_date__date를 기준으로 내림차순 정렬합니다.
    attendance_records = Attendance.objects.filter(user=student_from_session).order_by('-date')
    all_students = Student.objects.all()

    # 모든 학생들의 출결 상태를 업데이트합니다. available_date__date를 기준으로 상태를 업데이트하도록 변경하였습니다.
    for student in all_students:
        student.attendance_status = "출석" if student.attendance_set.filter(date=date.today()).exists() else "결석"

    context = {
        'student': student_from_session,
        'todays_attendance': todays_attendance,
        'form': form,
        'attendance_records': attendance_records,
        'all_students': all_students,
        'todays_attendance': todays_attendance,
        'message': message,
        'days_left_to_sept_twelve': days_left_to_sept_twelve,
        'days_left_to_thousand_days' : days_left_to_thousand_days
    }

    return render(request, 'dashboard.html', context)

from datetime import date

def check_in(request):
    if 'student_id' not in request.session:
        return redirect('attendances:user_login')

    student_id = request.session['student_id']
    student = Student.objects.get(student_id=student_id)

    # 오늘 날짜를 가져와서 출석 정보를 확인합니다.
    today = date.today()
    try:
        today_attendance = Attendance.objects.get(user=student, date=today)
    except Attendance.DoesNotExist:
        # 출석 정보가 없으면 생성합니다.
        today_attendance = Attendance.objects.create(user=student, date=today)

    return redirect('attendances:dashboard')

from datetime import date, timedelta

def get_this_week_range():
    today = date.today()
    start_date = today - timedelta(days=today.weekday())
    end_date = start_date + timedelta(days=6)
    return start_date, end_date, today.weekday()


def analyze_attendance_per_week(attendance_records, today_weekday):
    analyzed_data = {}
    current_date = date.today()
    one_week = timedelta(days=7)

    # 최대 5주치의 데이터를 분석합니다.
    for week_number in range(5):
        start_date = current_date - timedelta(days=(today_weekday + 1))  # 현재 주의 월요일로 설정
        end_date = start_date + timedelta(days=6)  # 현재 주의 일요일로 설정

        # 해당 주에 출석한 횟수를 세어 analyzed_data에 추가합니다.
        weekly_attendance_count = attendance_records.filter(date__range=[start_date, end_date]).count()
        analyzed_data[week_number] = {
            'count': weekly_attendance_count,
            'start_date': start_date,
            'end_date': end_date,
        }

        current_date -= one_week  # 이전 주로 이동

    return analyzed_data


def attendance_list(request):
    if 'student_id' not in request.session:
        return redirect('attendances:user_login')

    student_id = request.session['student_id']
    student = Student.objects.get(student_id=student_id)

    # 해당 학생의 출석 기록을 가져옵니다.
    attendance_records = Attendance.objects.filter(user=student).order_by('-date')

    # 이번 주 기간과 오늘의 요일을 가져옵니다.
    start_date, end_date, today_weekday = get_this_week_range()

    # 해당 학생의 이번 주 출석 기록을 가져옵니다.
    this_week_attendance_records = attendance_records.filter(date__range=[start_date, end_date])

    # 이번 주 출석 횟수를 세는 함수를 호출하여 분석합니다.
    analyzed_attendance = analyze_attendance_per_week(this_week_attendance_records, today_weekday)

    return render(request, 'attendance_list.html', {'student': student, 'attendance_records': this_week_attendance_records, 'analyzed_attendance': analyzed_attendance})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('attendances:user_login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def all_attendance_list(request):
    student_id_in_session = request.session.get('student_id')
    student_from_session = Student.objects.filter(student_id=student_id_in_session).first()

    if not student_from_session:
        return redirect('attendances:user_login')

    selected_date_str = request.GET.get('date')
    if selected_date_str:
        try:
            selected_date = datetime.strptime(selected_date_str, '%Y-%m-%d').date()
        except ValueError:
            # 잘못된 형식의 날짜가 입력된 경우 오늘 날짜로 설정
            selected_date = date.today()
    else:
        selected_date = date.today()

    all_students = Student.objects.all()

    # 모든 학생들의 출결 상태를 업데이트합니다.
    for student in all_students:
        attendance_status = "출석" if student.attendance_set.filter(date=selected_date).exists() else "결석"
        setattr(student, 'attendance_status', attendance_status)

    # 선택한 날짜의 출석과 결석한 학생들을 필터링합니다.
    attendance_present_students = [student for student in all_students if student.attendance_status == "출석"]
    attendance_absent_students = [student for student in all_students if student.attendance_status == "결석"]

    return render(request, 'all_attendance_list.html', {
        'student': student_from_session,
        'all_students': all_students,
        'attendance_present_students': attendance_present_students,
        'attendance_absent_students': attendance_absent_students,
        'selected_date': selected_date_str,
    })

def notice(request):
    query = request.GET.get('q')
    base_notices = Notice.objects.all().order_by('-created_at')  # 기본적으로 모든 공지사항을 날짜 역순으로 정렬

    if query:
        filtered_notices = base_notices.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by('-created_at')
    else:
        filtered_notices = base_notices

    paginator = Paginator(filtered_notices, 4)  # 한 페이지에 4개의 공지사항을 보여줍니다.
    page_number = request.GET.get('page')
    notices = paginator.get_page(page_number)

    current_page_range = get_page_range_notice(notices)

    context = {
        'notices': notices,
        'current_page_range': current_page_range,
        'query': query
    }

    return render(request, 'notice.html', context)

def get_page_range_notice(page_obj, num_pages_to_show=10):
    current_index = page_obj.number - 1
    num_pages = page_obj.paginator.num_pages

    if num_pages <= num_pages_to_show:
        page_range = list(range(1, num_pages + 1))
    else:
        num_middle_pages = num_pages_to_show - 2
        half_num_middle_pages = num_middle_pages // 2

        if current_index <= half_num_middle_pages:
            page_range = list(range(1, num_pages_to_show))
        elif current_index >= num_pages - half_num_middle_pages - 1:
            page_range = list(range(num_pages - num_pages_to_show + 1, num_pages + 1))
        else:
            start_index = current_index - half_num_middle_pages
            end_index = current_index + half_num_middle_pages + 1
            page_range = list(range(start_index + 1, end_index))

    return page_range

from django.utils import timezone

def notice_add(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']

        # 공지사항 등록을 위한 데이터 처리 로직 작성
        # 필요에 따라 Notice 모델을 사용해서 데이터베이스에 저장
        # created_at 필드에 현재 시간 설정
        notice = Notice.objects.create(title=title, content=content, created_at=timezone.now())

        return redirect('attendances:notice')  # 공지사항 목록 페이지로 리디렉션

adios_attendance/attendances/templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
<title>{% block title %}Dashboard{% endblock %}</title>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=0.5, user-scalable=no"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div> <h1><img class="logo" src="{% static 'images/AdiosLogo.png' %}" alt="Adios Logo"></h1>
</div>
</body>
</html>
{% block content %}
<h1>Dashboard</h1>
<br>
<hr align="center" style="border: solid 5px #007BFF; width: 50%;"/>
<ul class="url-buttons">
    <li class="url-button">
        <a href="{% url 'attendances:attendance_list' %}" class="url-link">내 출석</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:notice' %}" class="url-link">공지</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_date_list' %}" class="url-link">투표</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_available_list' %}" class="url-link">연습 불가 날짜 & 사유</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:all_attendance_list' %}" class="url-link">전체 출석 목록</a>
    </li>
</ul>
<h3>{{ student.name }}님, 오늘도 즐거운 연습되세요!</h3>
{% if todays_attendance %}
<p>오늘은 이미 출석 체크하셨습니다.</p>
<h4>{{ message }}</h4>
{% else %}
    <form method="post" action="{% url 'attendances:check_in' %}">
    {% csrf_token %}
    <button type="submit">출석 체크</button>
</form>
{% endif %}
<button class="btn btn-primary"
        onclick="if (confirm('로그아웃 하시겠습니까?')) location.href='{% url 'attendances:user_login' %}';">
    로그아웃
</button>
{% endblock %}

adios_attendance/attendances/templates/notice.html
{% extends 'base.html' %}

{% block title %}공지사항{% endblock %}

{% block content %}
<style>
    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin: -10px; /* 추가: 카드 간 좌우 간격 설정 */
    }

    .col-md-4 {
        flex-basis: calc(20% - 20px);
        margin: 10px; /* 수정: 카드 간 좌우 간격 설정 */
    }

    .card {
        height: 100%;
    }

    .card-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .card-title {
        font-size: 18px; /* 글씨 크기 설정 */
        font-weight: bold; /* 굵기 설정 */
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .pagination {
        display: flex;
        justify-content: center;
    }

    .page-link {
        margin-right: 10px; /* 원하는 간격(px)으로 조정 */
    }
</style>

<h1>공지사항</h1>
<hr align=center style="border: solid 5px #007BFF; width: 100%;">
<ul class="url-buttons">
    <li class="url-button">
        <a href="{% url 'attendances:dashboard' %}" class="url-link">Dashboard</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:attendance_list' %}" class="url-link">내 출석</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:notice' %}" class="url-link">공지</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_date_list' %}" class="url-link">투표</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_available_list' %}" class="url-link">연습 불가 날짜 & 사유</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:all_attendance_list' %}" class="url-link">전체 출석 목록</a>
    </li>
</ul>
<button class="btn btn-primary" onclick="location.href='{% url 'attendances:notice_add' %}'">공지 등록</button>
<form method="get" action="{% url 'attendances:notice' %}">
    <input type="text" name="q" placeholder="검색어를 입력하세요">
    <button type="submit">검색</button>
</form>

{% if query %}
<p>검색어: "{{ query }}"</p>
{% endif %}

{% if notices %}
<div class="row">
    {% for notice in notices %}
    <div class="col-md-4 mb-4">
        <div class="border border-primary rounded p-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ notice.title }}</h5>
                    <p class="card-text">{{ notice.content }}</p>
                    <p class="card-text">{{ notice.created_at|date:"Y-m-d H:i" }}</p>
                    <a href="{% url 'attendances:notice_detail' notice.id %}" class="btn btn-primary">상세 정보 확인</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Notice Pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% endif %}

        {% for num in current_page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
                    <span class="page-link">
                        {{ num }}
                    </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% else %}
<p>등록된 공지가 없습니다.</p>
{% endif %}
{% endblock %}

adios_attendance/attendances/templates/notice_detail.html
<!-- notice_detail.html -->

{% extends 'base.html' %}

{% block title %}공지사항 상세 정보{% endblock %}

{% block content %}
<h1>공지사항 상세 정보</h1>
<hr align=center style="border: solid 5px #007BFF; width: 100%;">

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">저장</button>
</form>

<form action="{% url 'attendances:notice_delete' notice.id %}" method="post">
  {% csrf_token %}
  <button type="submit" onclick="return confirm('삭제하시겠습니까?')">삭제</button>
</form>

<br>
<a href="{% url 'attendances:notice' %}">목록으로 돌아가기</a>
<br>
<br>
{% endblock %}

adios_attendance/attendances/templates/practice_available_add.html
{% extends 'base.html' %}

{% block title %}연습 불가 날짜 & 사유 등록{% endblock %}

{% block content %}
<h1>연습 불가 날짜 & 사유 등록</h1>
<hr align=center style="border: solid 5px #007BFF; width: 100%;">
<form method="post" action="{% url 'attendances:practice_available_add' %}">
    {% csrf_token %}
    {{ form.as_p }}  {# 폼 필드들을 표시 #}
    <button type="submit">등록</button>
</form>

<br>
<a href="{% url 'attendances:practice_available_list' %}">목록으로 돌아가기</a>
<br>
<br>
{% endblock %}

adios_attendance/attendances/templates/practice_available_detail.html
<!-- practice_available_detail.html -->

{% extends 'base.html' %}

{% block title %}연습 불가 날짜 & 사유 상세 정보{% endblock %}

{% block content %}
<h1>연습 불가 날짜 & 사유 상세 정보</h1>
<hr align=center style="border: solid 5px #007BFF; width: 100%;">

<form method="post">
    {% csrf_token %}
    <p>작성자</p>
    <h3>{{ practice_available.student.name }}</h3>
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>

<form action="{% url 'attendances:delete_practice_available' practice_available.id %}" method="post">
    {% csrf_token %}
    <button type="submit" onclick="return confirm('삭제하시겠습니까?')">삭제</button>
</form>

<br>
<a href="{% url 'attendances:practice_available_list' %}">목록으로 돌아가기</a>
<br>
<br>
{% endblock %}

adios_attendance/attendances/templates/practice_available_list.html
{% extends 'base.html' %}

{% block title %}연습 불가 날짜 & 사유 목록{% endblock %}

{% block content %}
<style>
    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin: -10px; /* 추가: 카드 간 좌우 간격 설정 */
    }

    .col-md-4 {
        flex-basis: calc(20% - 20px);
        margin: 10px; /* 수정: 카드 간 좌우 간격 설정 */
    }

    .card {
        height: 100%;
    }

    .card-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .card-title {
        font-size: 18px; /* 글씨 크기 설정 */
        font-weight: bold; /* 굵기 설정 */
        text-overflow: ellipsis;
    }

    .pagination {
        display: flex;
        justify-content: center;
    }

    .page-link {
        margin-right: 10px; /* 원하는 간격(px)으로 조정 */
    }
</style>
<h1>연습 불가 날짜 & 사유 목록</h1>
<hr align=center style="border: solid 5px #007BFF; width: 100%;">
<ul class="url-buttons">
    <li class="url-button">
        <a href="{% url 'attendances:dashboard' %}" class="url-link">Dashboard</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:attendance_list' %}" class="url-link">내 출석</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:notice' %}" class="url-link">공지</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_date_list' %}" class="url-link">투표</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:practice_available_list' %}" class="url-link">연습 불가 날짜 & 사유</a>
    </li>
    <li class="url-button">
        <a href="{% url 'attendances:all_attendance_list' %}" class="url-link">전체 출석 목록</a>
    </li>
</ul>
<button class="btn btn-primary" onclick="location.href='{% url 'attendances:practice_available_add' %}'">연습 불가 날짜 & 사유 등록</button>

<form method="get" action="{% url 'attendances:practice_available_list' %}">
    <input type="text" name="q" placeholder="검색어를 입력하세요">
    <button type="submit">검색</button>
</form>

{% if query %}
<p>검색어: "{{ query }}"</p>
{% endif %}

{% if availables %}
<div class="row">
    {% for practice_available in availables %}
    <div class="col-md-4 mb-4">
        <div class="border border-primary rounded p-3">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ practice_available.date|date:"Y-m-d" }}   {{ practice_available.student.name }}</p>
                    <p class="card-text">{{ practice_available.content }}</p>
                    <a href="{% url 'attendances:practice_available_detail' practice_available.id %}" class="btn btn-primary">상세 정보 확인</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Practice Available Pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% endif %}

        {% for num in current_page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
                    <span class="page-link">
                        {{ num }}
                    </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% else %}
<p>등록된 내용이 없습니다.</p>
{% endif %}
{% endblock %}